# 1. Base Image
FROM node:20-alpine

# 2. Create app directory
WORKDIR /app

# 3. Install dependencies
COPY package*.json ./
RUN npm install --production

# 4. Copy application source code
COPY . .

# 6. Expose application port
EXPOSE 3000

# 7. Start the application
CMD ["node", "src/server.js"]